### ISSUE TITLE
use docker to construct the project faceing a error when run  `flask digest compile`

### ISSUE THREAD

**Issue by ipukio** [cookiecutter-flask/cookiecutter-flask#1359]
Project configuration:

| Option                               | Values                                                                                     |
| ------------------------------------ | ------------------------------------------------------------------------------------------ |
| `use_pipenv`                         | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                                           |
| `python_version`                     | <ul><li>- [ ] `3.10`</li><li>- [ ] `3.9`</li><li>- [ ] `3.8`</li><li>- [x] `3.7`</li></ul> |
| `node_version`                       | <ul><li>- [ ] `16`</li><li>- [ ] `14`</li><li>- [x] `12`</li></ul>                         |
| `use_heroku`                         | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                                           |
| Are you using Docker to run the app? | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                                           |

i just follow the docker steps,but meeting error when run `npm run-script build` 
the problem is AttributeError: module 'jinja2.ext' has no attribute 'with_'
i take time ,but i have no idea how can i solve it. any help will be appreciate!!!

```
> ccc@1.0.0 flask-static-digest /app
> flask digest compile

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 444, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 407, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/app/autoapp.py", line 3, in <module>
    from ccc.app import create_app
  File "/app/ccc/app.py", line 8, in <module>
    from ccc import commands, public, user
  File "/app/ccc/public/__init__.py", line 3, in <module>
    from . import views  # noqa
  File "/app/ccc/public/views.py", line 14, in <module>
    from ccc.extensions import login_manager
  File "/app/ccc/extensions.py", line 18, in <module>
    debug_toolbar = DebugToolbarExtension()
  File "/usr/local/lib/python3.7/site-packages/flask_debugtoolbar/__init__.py", line 53, in __init__
    loader=PackageLoader(__name__, 'templates'))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/local/lib/python3.7/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccc@1.0.0 flask-static-digest: `flask digest compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccc@1.0.0 flask-static-digest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-31T07_53_26_251Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccc@1.0.0 build:default: `NODE_ENV=production webpack --progress --color --optimization-minimize && npm run flask-static-digest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccc@1.0.0 build:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-31T07_53_26_267Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccc@1.0.0 build: `run-script-os`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccc@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-31T07_53_26_290Z-debug.log
```

**Comment by jamescurtin** [comment]
A number of Flask-related dependencies have upgraded recently & versions need to upgrade simultaneously. I'd start by comparing your requirements files against the ones in the template [here](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/requirements/prod.txt) and [here](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/requirements/dev.txt). Once they match, upgrade and then try re-building.

If this doesn't fix the problem, please feel free to re-open the issue!
