### ISSUE TITLE
`npm run-script build` fails with "AttributeError: module 'jinja2.ext' has no attribute 'with_'"

### ISSUE THREAD

**Issue by grigutis** [cookiecutter-flask/cookiecutter-flask#1422]
Project configuration:

| Option                               | Values                                                                                     |
| ------------------------------------ | ------------------------------------------------------------------------------------------ |
| `use_pipenv`                         | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                                           |
| `python_version`                     | <ul><li>- [ ] `3.10`</li><li>- [ ] `3.9`</li><li>- [X] `3.8`</li><li>- [ ] `3.7`</li></ul> |
| `node_version`                       | <ul><li>- [X] `16`</li><li>- [ ] `14`</li><li>- [ ] `12`</li></ul>                         |
| `use_heroku`                         | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                                           |
| Are you using Docker to run the app? | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                                           |

When doing a local installation, I get the following error at the `npm run-script build` step:
```
…
> pipenv run flask digest compile

Loading .env environment variables...
Traceback (most recent call last):
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask/cli.py", line 988, in main
    cli.main()
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask/cli.py", line 389, in load_app
    app = locate_app(import_name, name)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/home/grigutis/src/psconfig_web/autoapp.py", line 3, in <module>
    from psconfig_web.app import create_app
  File "/home/grigutis/src/psconfig_web/psconfig_web/app.py", line 8, in <module>
    from psconfig_web import commands, public, user
  File "/home/grigutis/src/psconfig_web/psconfig_web/public/__init__.py", line 3, in <module>
    from . import views  # noqa
  File "/home/grigutis/src/psconfig_web/psconfig_web/public/views.py", line 14, in <module>
    from psconfig_web.extensions import login_manager
  File "/home/grigutis/src/psconfig_web/psconfig_web/extensions.py", line 18, in <module>
    debug_toolbar = DebugToolbarExtension()
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 50, in __init__
    self.jinja_env = Environment(
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/grigutis/.local/share/virtualenvs/psconfig_web-TSmwCTeJ/lib/python3.8/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'
```

**Comment by grigutis** [comment]
After a quick investigation, it looks like [prod.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/requirements/prod.txt) and [Pipfile](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/Pipfile) are out of sync.

https://github.com/cookiecutter-flask/cookiecutter-flask/blob/74fde7c5927de0374ad55ccdcca28ba22ae86171/%7B%7Bcookiecutter.app_name%7D%7D/requirements/prod.txt#L37
https://github.com/cookiecutter-flask/cookiecutter-flask/blob/74fde7c5927de0374ad55ccdcca28ba22ae86171/%7B%7Bcookiecutter.app_name%7D%7D/Pipfile#L41

**Comment by jamescurtin** [comment]
Thanks for the issue!
