### ISSUE TITLE
Steps to deploy to Heroku

### ISSUE THREAD

**Issue by gcrsaldanha** [cookiecutter-flask/cookiecutter-flask#207]
Hi!

I'd like to know which steps you guys take to deploy a project using cookiecutter-flask to Heroku. I had to manually install dev dependencies so `npm run build` could be executed which sounded kind of weird to me..

Any help/guidance is appreciated!

Thank you!

**Comment by franc3000** [comment]
@gcrsaldanha were you able to deploy to Heroku successfully? I'm getting errors:

```

Starting process with command `gunicorn erdos.app:create_app\(\)`
[INFO] Starting gunicorn 19.7.1
[INFO] Listening at: http://0.0.0.0:16541 (4)
[INFO] Using worker: sync
[INFO] Booting worker with pid: 9
[INFO] Booting worker with pid: 10
[INFO] Booting worker with pid: 11
State changed from starting to up

[ERROR] Exception in worker process
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 364, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/app/erdos/app.py", line 19, in create_app
    register_extensions(app)
  File "/app/erdos/app.py", line 36, in register_extensions
    webpack.init_app(app)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_webpack/__init__.py", line 27, in init_app
    self._set_asset_paths(app)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_webpack/__init__.py", line 69, in _set_asset_paths
    "Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and "
```

**Comment by tabacof** [comment]
I am also having trouble with Heroku. Any help would be greatly appreciated.

**Comment by clearf** [comment]
I would appreciate input on this, too.

**Comment by bheklilr** [comment]
Bumping. I'm running into the same problem with WEBPACK_MANIFEST_PATH, even after several iterations of trying to set the path manually.  I've even logged into the heroku dyno, run the webpack build manually, then tried to start the server manually but this error persists.

**Comment by cgallemore** [comment]
I was able to get by this by adding the nodejs buildpack, for example:

heroku buildpacks:add --index=1 heroku/nodejs

I then added a release_tasks.py in the root directory that contained:

npm run build
flask db upgrade

That scripts builds the assets and upgrades the database.

Once you add the node.js build pack you should see the following when running heroku buildpacks:

1. heroku/nodejs
2. heroku/python

**Comment by cgallemore** [comment]
I forgot to add the part about updating your Procfile to have a release step, it should look like:

release: ./release_task.sh
web: gunicorn <app_name>.app:create_app\(\) -b 0.0.0.0:$PORT -w 3

**Comment by cgallemore** [comment]
@sloria Would this be useful information to document within the cookicutter?  I'd be happy to contribute back and add that if you think that's worth adding to the README.

**Comment by sloria** [comment]
@cgallemore Yes, I would welcome a PR documenting the Heroku deployment steps!

**Comment by essramos** [comment]
any update on this?

**Comment by sloria** [comment]
If anyone wants to carry on where https://github.com/sloria/cookiecutter-flask/pull/290 left off, I would appreciate it.

**Comment by TobKed** [comment]
I will deploy my app on Heroku soon, I will try to push this topic forward.

**Comment by TobKed** [comment]
I've created PR with enhanced support of Heroku deployment https://github.com/cookiecutter-flask/cookiecutter-flask/pull/560
