### ISSUE TITLE
npm run flask-server "ValueError: signal only works in main thread"

### ISSUE THREAD

**Issue by PegasusWang** [cookiecutter-flask/cookiecutter-flask#238]
when I run `npm run flask-server`, I got this error 

```
> FLASK_APP=$PWD/autoapp.py FLASK_DEBUG=1 flask run

 * Serving Flask-SocketIO app "autoapp"
 * Forcing debug mode on
 * Restarting with fsevents reloader
 * Debugger is active!
 * Debugger PIN: 228-328-364
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/cli.py", line 56, in run_server
    return run_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 438, in run_command
    use_debugger=debugger, threaded=with_threads)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 737, in run_simple
    reloader_type)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/_reloader.py", line 257, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
ValueError: signal only works in main thread
```
I search on google and got this: https://stackoverflow.com/questions/31264826/start-a-flask-application-in-separate-thread

It seems I can't use `debug=True` and `use_reloader=True` both. But it's useful reloading server when code changes in debug mode. Then I change autoapp.py like this:

```
# -*- coding: utf-8 -*-
"""Create an application instance."""
from flask.helpers import get_debug_flag

from myflaskapp.app import create_app
from myflaskapp.settings import DevConfig, ProdConfig

CONFIG = DevConfig if get_debug_flag() else ProdConfig
app = create_app(CONFIG)
app.run(debug=True, use_reloader=True)
```
and just run python autoapp.py, It works well.

**Comment by sshaginyan** [comment]
👍

**Comment by QGB** [comment]
楼主，我谷歌过来居然在这里碰见你，缘分啊哈哈 @Pegas

**Comment by coolbreezeqf** [comment]
``` shell
 FLASK_APP=app.py FLASK_DEBUG=1 flask run
 * Serving Flask-SocketIO app "app"
...
```

卸载 Flask-SocketIO `pip uninstall Flask-SocketIO` 后，就能正常运行
```
 FLASK_APP=app.py FLASK_DEBUG=1 flask run
 * Serving Flask app "app"
...
```

**Comment by Old-Su** [comment]
> ```shell
>  FLASK_APP=app.py FLASK_DEBUG=1 flask run
>  * Serving Flask-SocketIO app "app"
> ...
> ```
> 
> 卸载 Flask-SocketIO `pip uninstall Flask-SocketIO` 后，就能正常运行
> 
> ```
>  FLASK_APP=app.py FLASK_DEBUG=1 flask run
>  * Serving Flask app "app"
> ...
> ```

确实卸载之后就可以了,请问什么原因啊?

**Comment by jamescurtin** [comment]
Going to close this issue out, as it seems the problem was identified & the template does not currently use `Flask-SocketIO`. Thank you!
