### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by faxe1008** [cookiecutter-flask/cookiecutter-flask#281]
Hi,

I tried runnig your example. I modified package.json like this:

```
"scripts": {
    "build": "set NODE_ENV=development && webpack --progress --colors -p",
    "start": "set NODE_ENV=development && node dev-server ./webpack/config",
    "webpack-dev-server": "set NODE_ENV=debug && webpack-dev-server --port 2992 --hot --inline",
    "flask-server": "set FLASK_APP=$PWD/autoapp.py FLASK_DEBUG=1 flask run",
    "lint": "eslint \"assets/js/*.js\""
  },
```

I ran:
```
npm install
npm run-script build
npm start
```
This is the error I got:
 ```
set NODE_ENV=development && node dev-server ./webpack/config

module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\blatzfab\Documents\Github\IHSUPA\flask_webapp\ihsupa\dev-server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ihsupa@1.0.0 start: `set NODE_ENV=development && node dev-server ./webpack/config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ihsupa@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by fourth0100** [comment]
I guess the problem is windows install node_modules path.
google:
npm config set cache 
npm config set prefix 

---

https://github.com/sloria/cookiecutter-flask/issues/281
:
"build": "set NODE_ENV=production && node_modules\\.bin\\webpack.cmd --progress --colors -p",

---

my package.json scripts:

  "scripts": {
    "build": "set NODE_ENV=production && node_modules\\.bin\\webpack.cmd --progress --colors -p",
    "start": "concurrently -n \"WEBPACK,FLASK\" -c \"bgBlue.bold,bgMagenta.bold\" \"npm run webpack-dev-server\" \"npm run flask-server\"",
    "webpack-dev-server": "set NODE_ENV=debug&&webpack-dev-server --port 2992 --hot --inline",
    "flask-server": "SET FLASK_APP=autoapp.py&SET FLASK_DEBUG=1&flask run",
    "lint": "eslint \"assets/js/*.js\""
  },

**Comment by jamescurtin** [comment]
Closing this issue due to lack of activity; this project now supports running the app in Docker, which should hopefully address many issues with operating system incompatibilities!
