### ISSUE TITLE
Using React for Interactive Tables

### ISSUE THREAD

**Issue by pgierz** [cookiecutter-flask/cookiecutter-flask#669]
Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [x] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [x] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |

Hi,

I'd like to use ReactJS to include some responsive tables. I can generate the tables on the Python side and (I think) pass it to the Javascript as JSON. I'm not sure though, I'm more familiar with the Python side than JS ;-)

As a start, I'm trying to just get [this table](https://mdbootstrap.com/docs/react/tables/datatables/) to show up in the members-only page.

What I've done so far:

1. Install Docker, npm, etc
2. Clone the repo and run Cookiecutter to get my own name and whatnot
3. `npm install react`
4. `npm install react-bootstrap`
5. Made a file `queue.js`, which includes the code from the link above
6. Import that file in the `main.js` with `require(./queue.js)`

When I run `docker-compose build flask-dev`, I get:
```
Building flask-dev
Step 1/21 : ARG INSTALL_PYTHON_VERSION=${INSTALL_PYTHON_VERSION:-3.7}
Step 2/21 : FROM python:${INSTALL_PYTHON_VERSION}-slim-buster AS base
 ---> 3d8f801fc3db
Step 3/21 : RUN apt-get update
 ---> Using cache
 ---> cf4cf1b5666c
Step 4/21 : RUN apt-get install -y     curl     gcc
 ---> Using cache
 ---> f6e6ef30ba81
Step 5/21 : ARG INSTALL_NODE_VERSION=${INSTALL_NODE_VERSION:-12}
 ---> Using cache
 ---> 06b443157124
Step 6/21 : RUN curl -sL https://deb.nodesource.com/setup_${INSTALL_NODE_VERSION}.x | bash -
 ---> Using cache
 ---> 27b5bb5372e0
Step 7/21 : RUN apt-get install -y     nodejs     && apt-get -y autoclean
 ---> Using cache
 ---> 65d843b47c6b
Step 8/21 : WORKDIR /app
 ---> Using cache
 ---> 92557be429c1
Step 9/21 : COPY ["Pipfile", "shell_scripts/auto_pipenv.sh", "./"]
 ---> Using cache
 ---> 6a3587fecb82
Step 10/21 : RUN pip install pipenv
 ---> Using cache
 ---> ec3865712162
Step 11/21 : COPY . .
 ---> 761d4a1b17c0
Step 12/21 : RUN useradd -m sid
 ---> Running in e2faf2b8f01f
Removing intermediate container e2faf2b8f01f
 ---> 5b26560a41ab
Step 13/21 : RUN chown -R sid:sid /app
 ---> Running in 3fce19c9fcbb
Removing intermediate container 3fce19c9fcbb
 ---> 1805e4953726
Step 14/21 : USER sid
 ---> Running in fbb2accdf67b
Removing intermediate container fbb2accdf67b
 ---> 7d3230b828ed
Step 15/21 : ENV PATH="/home/sid/.local/bin:${PATH}"
 ---> Running in 1c47043038f8
Removing intermediate container 1c47043038f8
 ---> 62a7ec0ded97
Step 16/21 : RUN npm install
 ---> Running in 60b100f2267d
audited 7654 packages in 4.042s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container 60b100f2267d
 ---> f376d5d7bc66

Step 17/21 : FROM base AS development
 ---> f376d5d7bc66
Step 18/21 : RUN pipenv install --dev
 ---> Running in d164c30362a4
Creating a virtualenv for this project…
Pipfile: /app/Pipfile
Using /usr/local/bin/python (3.8.1) to create virtualenv…
⠼ Creating virtual environment...Already using interpreter /usr/local/bin/python
Using base prefix '/usr/local'
New python executable in /home/sid/.local/share/virtualenvs/app-4PlAip0Q/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/sid/.local/share/virtualenvs/app-4PlAip0Q
Installing dependencies from Pipfile.lock (2146c2)…
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Removing intermediate container d164c30362a4
 ---> afb8474eb640
Step 19/21 : EXPOSE 2992
 ---> Running in a965c30acd93
Removing intermediate container a965c30acd93
 ---> ef37c70e986d
Step 20/21 : EXPOSE 5000
 ---> Running in 04ae6b30c64c
Removing intermediate container 04ae6b30c64c
 ---> 6d178d86684f
Step 21/21 : CMD [ "pipenv", "run", "npm", "start" ]
 ---> Running in f85b6fbff879
Removing intermediate container f85b6fbff879
 ---> 109633c11912

Successfully built 109633c11912
Successfully tagged esm_viz_webapp-development:latest
```

However, when I then run the `up` command:
```
$ docker-compose up flask-dev

docker-compose up flask-dev                           
Creating network "esm_viz_webapp_default" with the default driver
Creating esm_viz_webapp_flask-dev_1 ... done
Attaching to esm_viz_webapp_flask-dev_1
flask-dev_1   | Loading .env environment variables…
flask-dev_1   | 
flask-dev_1   | > esm_viz_webapp@1.0.0 start /app
flask-dev_1   | > concurrently -n "WEBPACK,FLASK" -c "bgBlue.bold,bgMagenta.bold" "npm run webpack-watch" "npm run flask-server"
flask-dev_1   | 
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [WEBPACK] > esm_viz_webapp@1.0.0 webpack-watch /app
flask-dev_1   | [WEBPACK] > NODE_ENV=debug webpack --mode development --watch
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [FLASK] 
flask-dev_1   | [FLASK] > esm_viz_webapp@1.0.0 flask-server /app
flask-dev_1   | [FLASK] > pipenv run flask run --host=0.0.0.0
flask-dev_1   | [FLASK] 
flask-dev_1   | [FLASK] Loading .env environment variables...
flask-dev_1   | [FLASK]  * Serving Flask app "autoapp.py" (lazy loading)
flask-dev_1   | [FLASK]  * Environment: development
flask-dev_1   | [FLASK]  * Debug mode: on
flask-dev_1   | [FLASK]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
flask-dev_1   | [FLASK]  * Restarting with stat
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [WEBPACK] webpack is watching the files...
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [FLASK]  * Debugger is active!
flask-dev_1   | [FLASK]  * Debugger PIN: 189-313-508
flask-dev_1   | [WEBPACK] Hash: fc904ba2d48c7d88d16b
flask-dev_1   | [WEBPACK] Version: webpack 4.41.5
flask-dev_1   | [WEBPACK] Time: 2161ms
flask-dev_1   | [WEBPACK] Built at: 01/08/2020 8:23:50 AM
flask-dev_1   | [WEBPACK]                                                     Asset      Size    Chunks             Chunk Names
flask-dev_1   | [WEBPACK] _/node_modules/font-awesome/fonts/fontawesome-webfont.eot   162 KiB            [emitted]  
flask-dev_1   | [WEBPACK] _/node_modules/font-awesome/fonts/fontawesome-webfont.svg   434 KiB            [emitted]  
flask-dev_1   | [WEBPACK] _/node_modules/font-awesome/fonts/fontawesome-webfont.ttf   162 KiB            [emitted]  
flask-dev_1   | [WEBPACK]                    af7ae505a9eed503f8b8e6982036873e.woff2  75.4 KiB            [emitted]  
flask-dev_1   | [WEBPACK]                     fee66e712a8a08eef5805a46892932ad.woff  95.7 KiB            [emitted]  
flask-dev_1   | [WEBPACK]                                           img/favicon.ico  58.2 KiB            [emitted]  
flask-dev_1   | [WEBPACK]                                       main_css.bundle.css   230 KiB  main_css  [emitted]  main_css
flask-dev_1   | [WEBPACK]                                        main_css.bundle.js  8.25 KiB  main_css  [emitted]  main_css
flask-dev_1   | [WEBPACK]                                         main_js.bundle.js  1.59 MiB   main_js  [emitted]  main_js
flask-dev_1   | [WEBPACK] Entrypoint main_js = main_js.bundle.js
flask-dev_1   | [WEBPACK] Entrypoint main_css = main_css.bundle.css main_css.bundle.js
flask-dev_1   | [WEBPACK] [0] multi ./node_modules/font-awesome/css/font-awesome.css ./node_modules/bootstrap/dist/css/bootstrap.css ./assets/css/style.css 52 bytes {main_css} [built]
flask-dev_1   | [WEBPACK] [./assets/css/style.css] 325 bytes {main_css} [built]
flask-dev_1   | [WEBPACK] [./assets/img sync recursive .*] ./assets/img sync .* 178 bytes {main_js} [built]
flask-dev_1   | [WEBPACK] [./assets/img/favicon.ico] 59 bytes {main_js} [optional] [built]
flask-dev_1   | [WEBPACK] [./assets/js/main.js] 488 bytes {main_js} [built]
flask-dev_1   | [WEBPACK] [./assets/js/plugins.js] 85 bytes {main_js} [built]
flask-dev_1   | [WEBPACK] [./assets/js/queue.js] 2.88 KiB {main_js} [built] [failed] [1 error]
flask-dev_1   | [WEBPACK] [./assets/js/script.js] 36 bytes {main_js} [built]
flask-dev_1   | [WEBPACK] [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main_js} [built]
flask-dev_1   | [WEBPACK]     + 12 hidden modules
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [WEBPACK] ERROR in ./assets/js/queue.js
flask-dev_1   | [WEBPACK] Module build failed (from ./node_modules/babel-loader/lib/index.js):
flask-dev_1   | [WEBPACK] SyntaxError: /app/assets/js/queue.js: Unexpected token (513:4)
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [WEBPACK]   511 | 
flask-dev_1   | [WEBPACK]   512 |   return (
flask-dev_1   | [WEBPACK] > 513 |     <MDBDataTable
flask-dev_1   | [WEBPACK]       |     ^
flask-dev_1   | [WEBPACK]   514 |       striped
flask-dev_1   | [WEBPACK]   515 |       bordered
flask-dev_1   | [WEBPACK]   516 |       small
flask-dev_1   | [WEBPACK]     at Parser.raise (/app/node_modules/@babel/parser/lib/index.js:7012:17)
flask-dev_1   | [WEBPACK]     at Parser.unexpected (/app/node_modules/@babel/parser/lib/index.js:8405:16)
flask-dev_1   | [WEBPACK]     at Parser.parseExprAtom (/app/node_modules/@babel/parser/lib/index.js:9661:20)
flask-dev_1   | [WEBPACK]     at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:9237:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:9217:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:9083:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:9056:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeAssign (/app/node_modules/@babel/parser/lib/index.js:9015:21)
flask-dev_1   | [WEBPACK]     at Parser.parseParenAndDistinguishExpression (/app/node_modules/@babel/parser/lib/index.js:9799:28)
flask-dev_1   | [WEBPACK]     at Parser.parseExprAtom (/app/node_modules/@babel/parser/lib/index.js:9582:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:9237:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:9217:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:9083:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:9056:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeAssign (/app/node_modules/@babel/parser/lib/index.js:9015:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExpression (/app/node_modules/@babel/parser/lib/index.js:8965:23)
flask-dev_1   | [WEBPACK]     at Parser.parseReturnStatement (/app/node_modules/@babel/parser/lib/index.js:11059:28)
flask-dev_1   | [WEBPACK]     at Parser.parseStatementContent (/app/node_modules/@babel/parser/lib/index.js:10738:21)
flask-dev_1   | [WEBPACK]     at Parser.parseStatement (/app/node_modules/@babel/parser/lib/index.js:10690:17)
flask-dev_1   | [WEBPACK]     at Parser.parseBlockOrModuleBlockBody (/app/node_modules/@babel/parser/lib/index.js:11266:25)
flask-dev_1   | [WEBPACK]     at Parser.parseBlockBody (/app/node_modules/@babel/parser/lib/index.js:11253:10)
flask-dev_1   | [WEBPACK]     at Parser.parseBlock (/app/node_modules/@babel/parser/lib/index.js:11237:10)
flask-dev_1   | [WEBPACK]     at Parser.parseFunctionBody (/app/node_modules/@babel/parser/lib/index.js:10256:24)
flask-dev_1   | [WEBPACK]     at Parser.parseArrowExpression (/app/node_modules/@babel/parser/lib/index.js:10197:10)
flask-dev_1   | [WEBPACK]     at Parser.parseParenAndDistinguishExpression (/app/node_modules/@babel/parser/lib/index.js:9823:12)
flask-dev_1   | [WEBPACK]     at Parser.parseExprAtom (/app/node_modules/@babel/parser/lib/index.js:9582:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:9237:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:9217:21)
flask-dev_1   | [WEBPACK]     at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:9083:23)
flask-dev_1   | [WEBPACK]     at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:9056:23)
flask-dev_1   | [WEBPACK]  @ ./assets/js/main.js 28:0-21
flask-dev_1   | [WEBPACK] 
flask-dev_1   | [WEBPACK] ERROR in ./assets/js/main.js
flask-dev_1   | [WEBPACK] Module not found: Error: Can't resolve 'react' in '/app/assets/js'
flask-dev_1   | [WEBPACK]  @ ./assets/js/main.js 16:0-16
flask-dev_1   | [WEBPACK] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!assets/css/style.css:
flask-dev_1   | [WEBPACK]     Entrypoint mini-css-extract-plugin = *
flask-dev_1   | [WEBPACK]     [./node_modules/css-loader/dist/cjs.js!./assets/css/style.css] 1.46 KiB {mini-css-extract-plugin} [built]
flask-dev_1   | [WEBPACK]         + 1 hidden module
flask-dev_1   | [WEBPACK] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/bootstrap/dist/css/bootstrap.css:
flask-dev_1   | [WEBPACK]     Entrypoint mini-css-extract-plugin = *
flask-dev_1   | [WEBPACK]        2 modules
flask-dev_1   | [WEBPACK] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/font-awesome/css/font-awesome.css:
flask-dev_1   | [WEBPACK]     Entrypoint mini-css-extract-plugin = *
flask-dev_1   | [WEBPACK]        9 modules
```

It looks like a syntax error. After some reading, I learned that ReactJS uses something called JSX, which allows you to mix HTML and JS in the same file. If I'm understanding it correctly, then React isn't loaded properly? Any hints would be very greatly appreciated, and sorry for the beginner questions!

Cheers,
Paul

**Comment by pgierz** [comment]
Fixed this. If anyone is interested, here are some of my notes:

# Notes for Web App Development

1. Run `./cookiecutter-docker.sh`
2. Fill in the questions:
  * Pipenv: True
  * Python: 3.8
  * Node Version 12
  * Heroku False
3. Move the resulting project to the directory ~/Code/web_sandbox
4. Git init
5. See what the default webapp looks like with absolutely no changes. This assumes you have my shortcuts installed

```shell
$ dcb
$ dcup flask-dev
```
That seems to work pretty well so far. There are of course a few Python errors due to missing database initialisation; but that's ok. Let's first add a basic change to the home page template to see if we can get React to input some stuff:

Starting from commit `d547d42`, the `Pipfile.lock` is committed, these notes, and changes to the `home.html` template

We should be able to use npm to add React. Following http://ccoenraets.github.io/es6-tutorial-react/setup/ (Note I'm not sure if this guide is the best choice, since it talks about ECMAScript 6?):
0. Install npm (on MacOS: `brew install npm`). We get `npm --version = 6.13.4`
1. `npm init`
2. `npm install react react-dom --save-dev`
3. `npm install babel-core babel-loader webpack --save-dev`

At this point, the guide says we should generate a `webpack.config.js` file, which we already have. We skip this step.

Next, it wants to modify the `scripts` section of `package.json`. We also skip this step.

Let's see if we can rebuild and run. So, the new heading shows up, but there is nothing in the React div, since we don't have anything to display there yet.

To do that, let's include React and ReactDOM in the main.js file. Now we have:

```javascript
import React, { Component } from 'react';
```

However, this leads to:
```shell
flask-dev_1   | [WEBPACK] ERROR in ./assets/js/main.js
flask-dev_1   | [WEBPACK] Module not found: Error: Cant resolve react in /app/assets/js
```

Adding a `.dockerignore` file to stop it from copying the compiled node modules and instead install them in the container.

Adding a `.dockerignore` and running `npm install` inside the container seems to have solved the import problem. Next is to get it to display something.

So, if I add a basic string to `ReactDOM.render`, I get a string back, which also renders. However, I want to be able to display HTML; so I need to use `<p>...</p>`. This causes a syntax error:
```shell
flask-dev_1   | [WEBPACK] ERROR in ./assets/js/main.js
flask-dev_1   | [WEBPACK] Module build failed (from ./node_modules/babel-loader/lib/index.js):
flask-dev_1   | [WEBPACK] SyntaxError: /app/assets/js/main.js: Unexpected token (26:16)
flask-dev_1   | [WEBPACK]
flask-dev_1   | [WEBPACK]   24 | import ReactDOM from "react-dom";
flask-dev_1   | [WEBPACK]   25 |
flask-dev_1   | [WEBPACK] > 26 | ReactDOM.render(<p>"This is a test!"</p>, document.getElementById("hello_react"))
flask-dev_1   | [WEBPACK]      |                 ^
flask-dev_1   | [WEBPACK]   27 |
```

To get this to work, we need the **Babel Transpiler**. Following these instructions: https://babeljs.io/setup#installation
1. npm install --save-dev babel-loader @babel/core
2. npm install @babel/preset-env --save-dev
3. Create a `.babelrc`
4. npm install babel-preset-es2015 babel-preset-react
