### ISSUE TITLE
Fresh instance of cookiecutter issue with flask-static-digest

### ISSUE THREAD

**Issue by extant1** [cookiecutter-flask/cookiecutter-flask#675]
I'm not sure if this is a flask-static-digest issue or with the cookiecutter-flask so I'll start here before posting there.

Fresh install of cookiecutter-flask and ran:

npm install
npm run build
flask run

Error:  

> 127.0.0.1 - - [20/Jan/2020 21:17:44] "GET / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2463, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2449, in wsgi_app
>     response = self.handle_exception(e)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1866, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask_debugtoolbar\__init__.py", line 125, in dispatch_request
>     return view_func(**req.view_args)
>   File "F:\testies\testies\public\views.py", line 43, in home
>     return render_template("public/home.html", form=form)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
>     ctx.app,
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
>     rv = template.render(context)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "F:\testies\testies\templates\public\home.html", line 2, in top-level template code
>     {% extends "layout.html" %}
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
>     return concat(self.root_render_func(self.new_context(vars)))
>   File "F:\testies\testies\templates\public\home.html", line 16, in root
>     <div class="row">
>   File "F:\testies\testies\templates\layout.html", line 12, in root
> 
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask_static_digest\__init__.py", line 64, in static_url_for
>     return flask_url_for(endpoint, **merged_values)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
>     return appctx.app.handle_url_build_error(error, endpoint, values)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
>     reraise(exc_type, exc_value, tb)
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
>     endpoint, values, method=method, force_external=external
>   File "c:\users\whiskey maple\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2020, in build
>     raise BuildError(endpoint, values, method, self)
> werkzeug.routing.BuildError: Could not build url for endpoint 'static'. Did you forget to specify values ['filename']?

cache_manifest.json contents
`{"build\\af7ae505a9eed503f8b8e6982036873e.woff2": "build\\af7ae505a9eed503f8b8e6982036873e-af7ae505a9eed503f8b8e6982036873e.woff2", "build\\fee66e712a8a08eef5805a46892932ad.woff": "build\\fee66e712a8a08eef5805a46892932ad-fee66e712a8a08eef5805a46892932ad.woff", "build\\img\\favicon.ico": "\\build\\img\\favicon-36131e511cbaacdc9e850bf826d4d54c.ico", "build\\main_css.bundle.css": "build\\main_css.bundle-f6036b017961822a98a2d6ad97671b15.css", "build\\main_css.bundle.js": "build\\main_css.bundle-991191951844e8a1affb3c610d36e8da.js", "build\\main_js.bundle.js": "build\\main_js.bundle-caeac1c055adf0ae5413276372b29185.js", "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont.eot": "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont-674f50d287a8c48dc19ba404d20fe713.eot", "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont.svg": "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont-912ec66d7572ff821749319396470bde.svg", "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont.ttf": "build\\_\\node_modules\\font-awesome\\fonts\\fontawesome-webfont-b06871f281fee6b241d60582ae9369b9.ttf"}
`

Project configuration:
Windows Enviornment
FLASK_APP=autoapp.py
FLASK_ENV=development
FLASK_DEBUG=1

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [ ] `3.8`</li><li>- [X] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |

**Comment by extant1** [comment]
Looks to be an issue with flask static digest ok windows.
