### ISSUE TITLE
A clean checkout per the preferred instructions fails to build

### ISSUE THREAD

**Issue by yurzo** [cookiecutter-flask/cookiecutter-flask#696]
```(base) damian.yurzola@dev-damian-yurzola2:~/flask/cookiecutter-flask$ ./cookiecutter-docker.sh
full_name [Steven Loria]:
email [sloria1@gmail.com]:
github_username [sloria]:
project_name [My Flask App]:
app_name [my_flask_app]:
project_short_description [A flasky app.]:
Select use_pipenv:
1 - no
2 - yes
Choose from 1, 2 (1, 2) [1]:
Select python_version:
1 - 3.8
2 - 3.7
3 - 3.6
Choose from 1, 2, 3 (1, 2, 3) [1]:
Select node_version:
1 - 12
2 - 10
Choose from 1, 2 (1, 2) [1]:
Select use_heroku:
1 - no
2 - yes
Choose from 1, 2 (1, 2) [1]:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/hooks.py", line 83, in run_script
    proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/generate.py", line 236, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/hooks.py", line 144, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/hooks.py", line 128, in run_script_with_context
    run_script(temp.name, cwd)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/hooks.py", line 99, in run_script
    raise FailedHookException(
cookiecutter.exceptions.FailedHookException: Hook script failed (error: [Errno 2] No such file or directory: '/build/my_flask_app')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/shutil.py", line 698, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/__main__.py", line 9, in <module>
    main(prog_name="cookiecutter")
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/cli.py", line 112, in main
    cookiecutter(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/main.py", line 90, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/generate.py", line 293, in generate_files
    _run_hook_from_repo_dir(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/generate.py", line 239, in _run_hook_from_repo_dir
    rmtree(project_dir)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/utils.py", line 42, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "/usr/local/lib/python3.8/shutil.py", line 700, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/utils.py", line 31, in force_delete
    os.chmod(path, stat.S_IWRITE)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'```

**Comment by jamescurtin** [comment]
It seems as if your local filesystem isn't being properly mounted to the project-gen container. Running `cookiecutter-docker.sh` with the default settings is effectively the same as running 

```console
$ docker run -i -t -v ${PWD}:/build -w /build cookiecutter-docker .
```

I'm guessing that it has something to do with your terminal not handling `${PWD}` correctly. Could you confirm your OS and which terminal you're using?

**Comment by yurzo** [comment]
The problem is that user: sid does not exist on the root installation so effectively the sid user inside docker has no permission to create files on the host.
I suppose that if a sid user is the one that cloned the repo, this would work.
I tried a couple things but don't yet know how to solve it.

**Comment by derrickberg-dev** [comment]
I have the same problem, using bash on Red Hat Enterprise Linux 8
