### ISSUE TITLE
Installing with cookiecutter produces a webpack-watch error

### ISSUE THREAD

**Issue by yurzo** [cookiecutter-flask/cookiecutter-flask#697]
The failing snippet:
```
flask-dev_1   | [WEBPACK] Error: EACCES: permission denied, open '/app/my_flask_app/static/build/fee66e712a8a08eef5805a46892932ad.woff'
flask-dev_1   | [WEBPACK] npm ERR! code ELIFECYCLE
flask-dev_1   | [WEBPACK] npm ERR! errno 1
flask-dev_1   | [WEBPACK] npm ERR! my_flask_app@1.0.0 webpack-watch: `NODE_ENV=debug webpack --mode development --watch`
flask-dev_1   | [WEBPACK] npm ERR! Exit status 1
flask-dev_1   | [WEBPACK] npm ERR!
flask-dev_1   | [WEBPACK] npm ERR! Failed at the my_flask_app@1.0.0 webpack-watch script.
flask-dev_1   | [WEBPACK] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
flask-dev_1   | [WEBPACK]
flask-dev_1   | [WEBPACK] npm ERR! A complete log of this run can be found in:
flask-dev_1   | [WEBPACK] npm ERR!     /home/sid/.npm/_logs/2020-02-11T18_01_16_275Z-debug.log
flask-dev_1   | [WEBPACK] npm run webpack-watch exited with code 1
```

This is the content on the log file referred above:

```
(base) damian.yurzola@dev-damian-yurzola2:~$ docker exec -it 6c32a39f0be2 bash
sid@6c32a39f0be2:/app$ cat /home/sid/.npm/_logs/2020-02-11T18_01_16_275Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'webpack-watch' ]
2 info using npm@6.13.4
3 info using node@v12.15.0
4 verbose run-script [ 'prewebpack-watch', 'webpack-watch', 'postwebpack-watch' ]
5 info lifecycle my_flask_app@1.0.0~prewebpack-watch: my_flask_app@1.0.0
6 info lifecycle my_flask_app@1.0.0~webpack-watch: my_flask_app@1.0.0
7 verbose lifecycle my_flask_app@1.0.0~webpack-watch: unsafe-perm in lifecycle true
8 verbose lifecycle my_flask_app@1.0.0~webpack-watch: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/home/sid/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle my_flask_app@1.0.0~webpack-watch: CWD: /app
10 silly lifecycle my_flask_app@1.0.0~webpack-watch: Args: [ '-c', 'NODE_ENV=debug webpack --mode development --watch' ]
11 silly lifecycle my_flask_app@1.0.0~webpack-watch: Returned: code: 1  signal: null
12 info lifecycle my_flask_app@1.0.0~webpack-watch: Failed to exec webpack-watch script
13 verbose stack Error: my_flask_app@1.0.0 webpack-watch: `NODE_ENV=debug webpack --mode development --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid my_flask_app@1.0.0
15 verbose cwd /app
16 verbose Linux 4.4.0-170-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack-watch"
18 verbose node v12.15.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error my_flask_app@1.0.0 webpack-watch: `NODE_ENV=debug webpack --mode development --watch`
22 error Exit status 1
23 error Failed at the my_flask_app@1.0.0 webpack-watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

This was an all-default cookiecutter launched via: `my_flask_app$ docker-compose up flask-dev`

**Comment by jamescurtin** [comment]
What is the relationship between this issue and the one you filed in https://github.com/cookiecutter-flask/cookiecutter-flask/issues/696? That is, was the project generated with errors from the last bug report used for this one? If it was, let's make sure you are first able to generate a clean project without any errors before diving into this issue.

A general though, though; this looks to be a file permission issue (`EACCES: permission denied, open '/app/my_flask_app/static/build/fee66e712a8a08eef5805a46892932ad.woff'`). That file is generated by webpack; that webpack can't write it to disk suggests there's an issue with mounting the local application directory into the container ([here](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/e942c99e23218b17337c5d27af8a9518b63510a9/%7B%7Bcookiecutter.app_name%7D%7D/docker-compose.yml#L9)).

**Comment by yurzo** [comment]
@jamescurtin: Thanks for your prompt answer. There was in principle no relationship between the issues. They were independently reproduced.
I'll check on the mounting as you suggest and report back.

**Comment by yurzo** [comment]
@jamescurtin as you suspected they are related. I'll comment my findings on the other one.
