### ISSUE TITLE
RUN npm run-script build fails in docker with webpack-cli unkown argument error.

### ISSUE THREAD

**Issue by jcrotts** [cookiecutter-flask/cookiecutter-flask#954]
I'm seeing this on master on both Ubuntu 18.04 and OSX.
Thanks for your time.

Output from docker build:
```Building flask-dev
Step 1/37 : ARG INSTALL_PYTHON_VERSION=${INSTALL_PYTHON_VERSION:-PYTHON_VERSION_NOT_SET}
Step 2/37 : ARG INSTALL_NODE_VERSION=${INSTALL_NODE_VERSION:-NODE_VERSION_NOT_SET}
Step 3/37 : FROM node:${INSTALL_NODE_VERSION}-buster-slim AS node
 ---> 63d87d6740f6

Step 4/37 : FROM python:${INSTALL_PYTHON_VERSION}-slim-buster AS builder
 ---> 0f59d947500d
Step 5/37 : WORKDIR /app
 ---> Using cache
 ---> ec4c06aed8aa
Step 6/37 : COPY --from=node /usr/local/bin/ /usr/local/bin/
 ---> Using cache
 ---> 4aaa2fadfe62
Step 7/37 : COPY --from=node /usr/lib/ /usr/lib/
 ---> Using cache
 ---> 7c78a9879f27
Step 8/37 : COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
 ---> Using cache
 ---> a173e716fc0a
Step 9/37 : COPY requirements requirements
 ---> Using cache
 ---> 7744bd357e52
Step 10/37 : RUN pip install --no-cache -r requirements/prod.txt
 ---> Using cache
 ---> 1c8c7a9d4019
Step 11/37 : COPY package.json ./
 ---> Using cache
 ---> fa097edcf71e
Step 12/37 : RUN npm install
 ---> Using cache
 ---> 132cef68b388
Step 13/37 : COPY webpack.config.js autoapp.py ./
 ---> Using cache
 ---> 70db530e6cfc
Step 14/37 : COPY my_flask_app my_flask_app
 ---> Using cache
 ---> e9a6c0cc56c6
Step 15/37 : COPY assets assets
 ---> Using cache
 ---> a69e2136815b
Step 16/37 : COPY .env.example .env
 ---> Using cache
 ---> 3d24f8df1d36
Step 17/37 : RUN npm run-script build
 ---> Running in cd3b709f5bf7

> my_flask_app@1.0.0 build /app
> run-script-os


> my_flask_app@1.0.0 build:default /app
> NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest

[webpack-cli] Unknown argument: --colors
Did you mean --color?
[webpack-cli] Unknown argument: -p
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my_flask_app@1.0.0 build:default: `NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the my_flask_app@1.0.0 build:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-12T23_56_32_443Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my_flask_app@1.0.0 build: `run-script-os`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the my_flask_app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-12T23_56_32_476Z-debug.log
ERROR: Service 'flask-dev' failed to build : The command '/bin/sh -c npm run-script build' returned a non-zero code: 2
```

Downgrading webpack-cli to 3.3.12 in package.json gives the following:
```

ERROR in ./assets/css/style.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ValidationError: Invalid options object. Mini CSS Extract Plugin Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'hmr'. These properties are valid:
   object { publicPath?, esModule?, modules? }
    at validate (/app/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.pitch (/app/node_modules/mini-css-extract-plugin/dist/loader.js:53:29)
 @ multi ./node_modules/@fortawesome/fontawesome-free/css/all.css ./node_modules/bootstrap/dist/css/bootstrap.css ./assets/css/style.css main_css[2]

ERROR in ./node_modules/@fortawesome/fontawesome-free/css/all.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ValidationError: Invalid options object. Mini CSS Extract Plugin Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'hmr'. These properties are valid:
   object { publicPath?, esModule?, modules? }
    at validate (/app/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.pitch (/app/node_modules/mini-css-extract-plugin/dist/loader.js:53:29)
 @ multi ./node_modules/@fortawesome/fontawesome-free/css/all.css ./node_modules/bootstrap/dist/css/bootstrap.css ./assets/css/style.css main_css[0]

ERROR in ./node_modules/bootstrap/dist/css/bootstrap.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ValidationError: Invalid options object. Mini CSS Extract Plugin Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'hmr'. These properties are valid:
   object { publicPath?, esModule?, modules? }
    at validate (/app/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.pitch (/app/node_modules/mini-css-extract-plugin/dist/loader.js:53:29)
 @ multi ./node_modules/@fortawesome/fontawesome-free/css/all.css ./node_modules/bootstrap/dist/css/bootstrap.css ./assets/css/style.css main_css[1]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my_flask_app@1.0.0 build:default: `NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the my_flask_app@1.0.0 build:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T00_01_31_794Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my_flask_app@1.0.0 build: `run-script-os`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the my_flask_app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T00_01_31_829Z-debug.log
ERROR: Service 'flask-dev' failed to build : The command '/bin/sh -c npm run-script build' returned a non-zero code: 2
```

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [x] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [x] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by Mogmi95** [comment]
Ah, looks like someone had the same problem. I was getting super confused because it worked on my home computer and now that I'm trying to deploy it doesn't...

After some researches, it looks like the culprit is `mini-css-extract-plugin`, which updated from 1.2.1 on my working version to 1.3.1 on the non working one.

A `$ npm install mini-css-extract-plugin@1.2.1` in the docker container fixed the problem. Fixing the version inside the `package.json` might just be a solution, but maybe you'll want to make it compatible with the 1.3.1 so I won't create a pull request for that.

I noticed some weird options to webpack during the process too, I'll open a new issue for that.

Thanks for the tool, it's awesome!

**Comment by jamescurtin** [comment]
Thank you for reporting! This is addressed in the PR linked above. Sorry for the inconvenience!

**Comment by jcrotts** [comment]
Thanks for the quick fix!
