### ISSUE TITLE
template app_name folder not getting renamed?

### ISSUE THREAD

**Issue by uBadRequest** [cookiecutter-flask/cookiecutter-flask#993]
I am attempting to use the docker method, using the default configuration. I'm pretty sure there is no problem mounting the current directory.

There must be some sort of issue with python converting the folder name to the variable {{cookiecutter.app_name}} because if i set app_name to {{cookiecutter.app_name}}, it says it already exists, anything else it says it doesn't exist. 

I have no idea what I could possibly be doing wrong... 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 83, in run_script
    proc = subprocess.Popen(script_command, shell=run_thru_shell, cwd=cwd)
  File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 94, in run_script
    raise FailedHookException('Hook script failed (error: {})'.format(os_error))
cookiecutter.exceptions.FailedHookException: Hook script failed (error: [Errno 2] No such file or directory: '/build/my_flask_app')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/__main__.py", line 9, in <module>
    main(prog_name="cookiecutter")
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 293, in generate_files
    _run_hook_from_repo_dir(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 240, in _run_hook_from_repo_dir
    rmtree(project_dir)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/utils.py", line 34, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "/usr/local/lib/python3.9/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/utils.py", line 25, in force_delete
    os.chmod(path, stat.S_IWRITE)
FileNotFoundError: [Errno 2] No such file or directory: '/build/my_flask_app'
```

**Comment by uBadRequest** [comment]
I noticed in other issues it seemed that the issue was thought to be with pwd ? 
![image](https://user-images.githubusercontent.com/47282747/104059767-bcb4da00-51ed-11eb-8276-4241c3a2540b.png)

**Comment by jamescurtin** [comment]
That's an unusual issue: I'm unable to reproduce the error (using either `cookiecutter-docker.sh` or the bash command from your screenshot) on MacOS running Docker 3.0.4.

What OS and Docker version are you using? Two other things to try are making sure you've pulled the latest changes from `master` and that you re-build the docker image (I think its unlikely these are related, but doing so makes sure we're both running the same thing).

It looks like the traceback originates from [this post-gen hook](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/17d4944121e8fcbad5aa08a6570358e4fde417e8/hooks/post_gen_project.py#L27) where unused files (based on the options you chose in the prompt) are deleted. I'd recommend adding a breakpoint to that function, which should allow you to inspect the environment (_e.g._ `os.listdir()`). Alternatively, what happens if you delete that hook file entirely?

**Comment by jamescurtin** [comment]
Strike that: it looks like [this issue](https://github.com/cookiecutter-flask/cookiecutter-flask/issues/696#issuecomment-584845626) is related.

Would you be able to try deleting [these two lines](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/Dockerfile#L6-L7) from the Dockerfile, then try generating a project?

I think you might be encountering a permission issue with the `sid` user. If so, I can put up a PR to resolve, but want to make sure this solution fixes your problem before I do.

**Comment by coxoperationsengineer** [comment]
I can confirm that removing those two lines fixed this issue for me on Ubuntu 20.04.1

**Comment by baasman** [comment]
I'm running into the same issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 83, in run_script
    proc = subprocess.Popen(script_command, shell=run_thru_shell, cwd=cwd)
  File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/mdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 94, in run_script
    raise FailedHookException('Hook script failed (error: {})'.format(os_error))
cookiecutter.exceptions.FailedHookException: Hook script failed (error: [Errno 2] No such file or directory: '/build/mdl')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/build/mdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/__main__.py", line 9, in <module>
    main(prog_name="cookiecutter")
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 293, in generate_files
    _run_hook_from_repo_dir(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 240, in _run_hook_from_repo_dir
    rmtree(project_dir)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/utils.py", line 34, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "/usr/local/lib/python3.9/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/utils.py", line 25, in force_delete
    os.chmod(path, stat.S_IWRITE)
FileNotFoundError: [Errno 2] No such file or directory: '/build/mdl'
```

I'm on centos 7. I've tried deleting the two lines in the Dockerfile, but I'm still getting the same error.

**Comment by baasman** [comment]
UPDATE: After repulling the image + removing the two lines - it works!

**Comment by jamescurtin** [comment]
Thanks for reporting--PR referenced above should resolve the issue!
